language: python
python:
  - "3.5"

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - llvm

before_script:
  # print interesting versions

    #- sudo update-alternatives --install /usr/bin/clang clan /usr/bin/clang-3.5 90
    #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - python --version
  - python -c "import numpy as np; print( np.__version__ )"
  - python -c "import h5py as h5; print( h5.__version__ )"
  - ulimit -c unlimited
script:
  - python -c "import numba; print (numba.__file__)"
